/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.universidad.vista.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Evaluacion;
import co.edu.eam.ingesoft.desarrollo.universidad.vista.controladores.ControladorCrearCalificacion;

/**
 *
 * @author dir_software
 */
public class VentanaCrearCalificacion extends javax.swing.JInternalFrame {

	static final Double CIEN = 100.0;
	private ControladorCrearCalificacion controlador;
    /**
     * Creates new form VentanaCrearCalificacion
     */
    public VentanaCrearCalificacion() {
    	
    	initComponents();
    	controlador = new ControladorCrearCalificacion();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);        
        setClosable(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcodigoasignatura = new javax.swing.JTextField();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnombreasignatura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCalificaciones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfnombrecal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfnombrepor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfporcentajenoasignado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnQuitarCalificacion = new javax.swing.JButton();

        setTitle("Administrar Calificaciones Curso");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10icono.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel1.setText("Codigo");

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        tfnombreasignatura.setEditable(false);

        jLabel3.setText("Curso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnombreasignatura)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones Curso"));

        tablaCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Porcentaje"
            }
        ));
        jScrollPane1.setViewportView(tablaCalificaciones);

        jLabel5.setText("Nombre");

        jLabel6.setText("Porcentaje");

        jLabel7.setText("No Asignado");

        tfporcentajenoasignado.setEditable(false);
        tfporcentajenoasignado.setToolTipText("Porcentaje faltante por asignar");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculation1.png"))); // NOI18N
        jButton1.setToolTipText("Agregar Calificacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnQuitarCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multiplication.png"))); // NOI18N
        btnQuitarCalificacion.setToolTipText("Quitar Calificacion Seleccionada");
        btnQuitarCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarCalificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfporcentajenoasignado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(tfnombrepor, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tfnombrecal, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitarCalificacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombrecal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfnombrepor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfporcentajenoasignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuitarCalificacion)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	try{
    		Curso curso = (Curso) jComboBox1.getSelectedItem();
    		String nombre = tfnombrecal.getText();
    		double porcentaje = Double.parseDouble(tfnombrepor.getText());
    		double porcentajeCurso = calcularPorcentaje();
    		if(porcentajeCurso < CIEN){
    			controlador.crearEvaluacion(new Evaluacion(nombre, porcentaje, curso));
    			Double porcentajeCursos = calcularPorcentaje();
    			tfporcentajenoasignado.setText((CIEN - porcentajeCursos) + "");
    			//Metodo que lista las evaluaciones por un determinado curso
    			listarEvaluacionPorCurso();
    		}else{
    			JOptionPane.showMessageDialog(null,"El curso ya ocupo todo el porcentaje de las calificaciones");
    		}
    	}catch(Exception ex){
    		ex.printStackTrace();
    		JOptionPane.showMessageDialog(null, ex);
    	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
        // TODO add your handling code here:
    	String codigo = tfcodigoasignatura.getText();
    	try{
    		Asignatura asignatura = controlador.buscarAsignatura(codigo);
    		List<Curso> cursos = controlador.listarCursosPorAsignatura(asignatura);
    		String nombreAsignatura = asignatura.getNombre();
    		tfnombreasignatura.setText(nombreAsignatura);
    		
    		for(Curso curso : cursos){
    			jComboBox1.addItem(curso);
    		}
    	}catch (Exception ex){
    		JOptionPane.showMessageDialog(null, ex.getMessage());
    	}
    }//GEN-LAST:event_btnBuscarAsignaturaActionPerformed

    private void btnQuitarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarCalificacionActionPerformed
        // TODO add your handling code here:
        String nombre = (String) tablaCalificaciones.getValueAt(tablaCalificaciones.getSelectedRow(),0);
        if(nombre!=null){
        	eliminarEvaluacion(nombre);
        	listarEvaluacionPorCurso();
        	JOptionPane.showMessageDialog(null,"Evaluacion eliminada");
        }else{
        	JOptionPane.showMessageDialog(null,"Debe seleccionar una evaluacion de la tabla para eliminar");
        	
        }
    }//GEN-LAST:event_btnQuitarCalificacionActionPerformed
    
    private void eliminarEvaluacion(String nombre){
    	try{
    		//Obtenemos la lista de las evaluaciones
    		List<Evaluacion> evaluaciones = controlador.listarEvaluacionPorCurso((Curso) jComboBox1.getSelectedItem());
    		//Recorremos la lista de las evaluaciones
    		for(Evaluacion evaluacion : evaluaciones){
    			if(evaluacion.getNombre().equals(nombre)){
    				//Obtenemos el id de la evaluacion
    				long id = evaluacion.getId();
    				//Eliminamos la evaluacion
    				controlador.eliminarEvaluacion(id);
    			}
    		}
    	}catch(Exception ex){
    		
    	}
    }
    
    /**
     * Metodo que calcula el porcentaje de cada curso
     * 
     * @author Jhoan Sebastian Salazar Henao<br/>
     *         email: jsebastian48@hotmail.com <br/>
     *         Fecha: 27/09/2016<br/>
     * @return el porcentaje
     */
    public Double calcularPorcentaje(){
    	try{
    		//Porcentaje
    		double porcentaje = 0;
    		//Lista de evaluaciones
    		List<Evaluacion> evaluaciones = controlador.listarEvaluacionPorCurso((Curso) jComboBox1.getSelectedItem());
    		//For para recorrer la lista de evaluaciones
    		for(Evaluacion evaluacion : evaluaciones){
    			porcentaje += evaluacion.getPorcentaje();
    		}
    		return porcentaje;
    	}catch(Exception ex){
    		return 0.0;
    	}
    }
    
    /**
     * Metodo que lista las evaluaciones por un curso determinado y los almacena en la tabla calificaciones
     * @author Jhoan Sebastian Salazar Henao<br/>
     *         email: jsebastian48@hotmail.com <br/>
     *         Fecha: 27/09/2016<br/>
     */
    public void listarEvaluacionPorCurso(){
    	try{
    		//Obtenemos la lista de las evaluaciones
    		List<Evaluacion> evaluaciones = controlador.listarEvaluacionPorCurso((Curso) jComboBox1.getSelectedItem());
    		//Definimos el modelo de la tabla
    		DefaultTableModel model = (DefaultTableModel) tablaCalificaciones.getModel();
    		//Asignamos 0 filas en la tabla
    		model.setRowCount(0);
    		//Recorremos la lista de evaluaciones 
    		for(Evaluacion evaluacion : evaluaciones){
    			Object[] fila = new Object[2];
    			//Obtenemos el nombre de la evaluacion
    			fila[0] = evaluacion.getNombre();
    			//Obtenemos el porcentaje de la evaluacion
    			fila[1] = evaluacion.getPorcentaje();
    			model.addRow(fila);
    		}
    	}catch(Exception ex){
    		JOptionPane.showMessageDialog(null,ex);
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JButton btnQuitarCalificacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCalificaciones;
    private javax.swing.JTextField tfcodigoasignatura;
    private javax.swing.JTextField tfnombreasignatura;
    private javax.swing.JTextField tfnombrecal;
    private javax.swing.JTextField tfnombrepor;
    private javax.swing.JTextField tfporcentajenoasignado;
    // End of variables declaration//GEN-END:variables
	
	
}
