/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.universidad.vista.gui;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Asignatura;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Curso;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.Nota;
import co.edu.eam.ingesoft.desarrollo.universidad.persistencia.modelo.entidades.RegistroCurso;
import co.edu.eam.ingesoft.desarrollo.universidad.vista.controladores.ControladorVerCalificaciones;

/**
 *
 * @author dir_software
 */
public class VentanaVerCalificaciones extends javax.swing.JInternalFrame {

	private List<Curso> cursos;
	private ControladorVerCalificaciones controlador;
	
    /**
     * Creates new form VentanaIngresarCalificaciones
     */
    public VentanaVerCalificaciones() {
        initComponents();
        cursos=null;
        controlador = new ControladorVerCalificaciones();
         setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setResizable(false);
        setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfcodigoasignatura = new javax.swing.JTextField();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfnombreasignatura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();

        setTitle("Ver Calificaciones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom38.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom38.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel2.setText("Codigo");

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom37.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar Asignatura");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignaturaActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        tfnombreasignatura.setEditable(false);

        jLabel4.setText("Curso");

        comboCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCursoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfnombreasignatura)
                            .addComponent(comboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfcodigoasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombreasignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Nota 1", "Nota 2", "..", "...", "Nota N", "Definitiva"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
        // TODO add your handling code here:
    	cursos=null;
        String codigo = tfcodigoasignatura.getText();
        try{
        	Asignatura asignatura = controlador.buscarAsignatura(codigo);
        	if(asignatura !=null){
        		tfnombreasignatura.setText(asignatura.getNombre());
        		try{
        			cursos = controlador.listarCursosPorAsignatura(asignatura);
        			comboCurso.addItem("Seleccione un curso");
        			
        			for(Curso curso : cursos){
        				comboCurso.addItem(curso.getCodigo());
        			}
        		}catch(Exception ex){
        			ex.getStackTrace();
        		}
        	}
        }catch(Exception ex){
        	ex.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarAsignaturaActionPerformed

    private void comboCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCursoItemStateChanged
        // TODO add your handling code here:
    	String codigo = (String) comboCurso.getSelectedItem();
    	for(Curso curso : cursos){
    		if(curso.getCodigo().equals(codigo)){
    			try{
    				List<RegistroCurso> registroCursos = controlador.listarRegistrosCursoPorCurso(curso);
    				modeloTabla(registroCursos);
    			}catch(Exception ex){
    				JOptionPane.showMessageDialog(null,"El curso no tiene estudiantes registrados");
    				ex.printStackTrace();
    			}
    		}
    	}
    }//GEN-LAST:event_comboCursoItemStateChanged

    public void modeloTabla(List<RegistroCurso> registroCursos){
    	int cantidadNotas=0;
    	for(RegistroCurso registroCurso : registroCursos){
    		int notas = registroCurso.getNotas().size();
    		if(notas >= cantidadNotas){
    			cantidadNotas = notas;
    		}
    	}
    	DefaultTableModel model = (DefaultTableModel) tablaNotas.getModel();
    	model.setRowCount(0);
    	model.setColumnCount(0);
    	model.addColumn("Cedula");
    	model.addColumn("Nombre");
    	for(int i=1; i <= cantidadNotas; i++){
    		model.addColumn("Nota " + i);
    	}
    	model.addColumn("Definitiva");
    	
    }
    
    /**
     * Metodo que carga la tabla con los datos del curso elegido
     * @author Jhoan Sebastian Salazar Henao<br/>
     *         email: jsebastian48@hotmail.com <br/>
     *         Fecha: 28/09/2016<br/>
     * @param registroCursos, lista de registros del curso
     * @param model, tabla que se tiene que llenar
     * @param cantidadColumnas
     */
    private void cargarTabla (List<RegistroCurso> registroCursos, DefaultTableModel model, int cantidadColumnas){
    	int notas = cantidadColumnas - 3;
    	double definitiva = 0;
    	for(RegistroCurso registroCurso : registroCursos){
    		Object[] fila = new Object[cantidadColumnas];
    		fila[0] = registroCurso.getEstudiante().getCedula();
    		fila[1] = registroCurso.getEstudiante().getNombre();
    		List<Nota> nota = registroCurso.getNotas();
    		if(nota.size()==0){
    			for(int i = 0; i < notas; i++){
    				fila[i+2]="N/C";
    			}
    		}else{
    			if(nota.size() <= (cantidadColumnas - 3)){
    				for(int i = 0; i < notas; i++){
    					if(i <= nota.size()){
    						double n = nota.get(i).getValor();
    						JOptionPane.showMessageDialog(null, nota.get(i).getValor());
    						definitiva += n;
    						fila[i + 2]= n;
    					}else{
    						fila[i + 2] = "N/C";
    					}
    				}
    			}
    		}
    		fila[cantidadColumnas - 1] = definitiva / (cantidadColumnas - 3);
    		model.addRow(fila);
    		definitiva=0;
    	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JComboBox comboCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaNotas;
    private javax.swing.JTextField tfcodigoasignatura;
    private javax.swing.JTextField tfnombreasignatura;
    // End of variables declaration//GEN-END:variables
}
